name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask sqlalchemy pytest

      - name: Run tests
        run: |
          pytest --verbose || echo "No tests implemented, skipping."

      - name: Build Docker image
        run: |
          docker build -t art_community_app .

      - name: Push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag art_community_app <your-dockerhub-username>/art_community_app:latest
          docker push <your-dockerhub-username>/art_community_app:latest

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-azure-app-name>
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
