name: CI/CD Workflow for Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Step 3: Install Python dependencies
      - name: Install Flask and required libraries
        run: |
          python -m pip install --upgrade pip
          pip install flask sqlalchemy

      # Step 4: Set up the database
      - name: Initialize database
        run: |
          python database_setup.py
          python somedata.py

      # Step 5: Run tests (if applicable)
      - name: Run tests
        run: |
          pytest --verbose || echo "No tests found, continuing..."

  deploy:
    runs-on: ubuntu-latest
    needs: [setup-and-test]

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate Azure CLI
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy to Azure App Service
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: <your-azure-app-name>
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
